### ISSUE TITLE
Crashed in `bpf.rs:416:44`

### ISSUE THREAD

**Issue by xmh0511** [libpnet/libpnet#645] opened 2023-09-07 09:26 UTC
> thread 'main' panicked at 'misaligned pointer dereference: address must be a multiple of 0x4 but is 0x7f7f5900b00e'
> 
> /.cargo/registry/src/index.crates.io-6f17d22bba15001f/pnet_datalink-0.34.0/src/bpf.rs:416:44
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread caused non-unwinding panic. aborting.
zsh: abort      sudo cargo run

**Comment by frankplow** [comment] 2023-10-21 11:29
Possible duplicate of #641. Are you also using MacOS?

**Comment by xmh0511** [comment] 2023-10-23 03:09
> Are you also using MacOS?

Yes.

**Closed** 2024-05-30 16:39 UTC
